### ISSUE TITLE
TMDB - Add genres and browser

### ISSUE THREAD

**Issue by morpheasgr** [Sarlay/SunStream#1]
I was wondering whether current code state of cloudstream does allow unlimited search result listing/handling of pagination.

Since your approach is a unified interface for multiple sources I am making this feature request here.

TMDB offers categories/genres

Here's a talk about it, from the API side of things: https://www.themoviedb.org/talk/5daf6eb0ae36680011d7e6ee

Here's an example of how you can view a certain genre from the site.

https://www.themoviedb.org/genre/878-science-fiction/movie

And once an anime info provider is implemented and sources are implemented to use it, the same could be done.

An example application that lists genres for anime is the Saikou app :) I think it uses AniList, not sure though.

**Comment by ImranMZ** [comment]
It would be great 👌 just like ( Hdo box )...but it uses trakt

**Comment by Sarlay** [comment]
Thanks for the suggestion !
Its not planned to add genre search filter atm, I will implement it once cloudstream-3 has this feature (low priority for them too)
I will try to add genre such as 'sci-fi' or 'action' to the homepage of tmdb
