### ISSUE TITLE
Add `MyDramaList (MDL)` for Asian Content Database

### ISSUE THREAD

**Issue by bachig26** [Sarlay/SunStream#2]
### Describe your suggested feature

Add this in similar way as TMDB, as the asian contents are not available and this MDL Database (community project) will be good option to add on.

MDL API is available and there are many in GitHub but there is official API from [MyDramaList](https://mydramalist.com/), but you need to contact them via E-Mail.
MDL API Request: https://mydramalist.com/api_request

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Sarlay** [comment]
Thank you for the suggestion but its not planned atm
Some drama will still be available through TMDB nonetheless
